## xyloTermux - termux.properties
## https://github.com/xylo/xyloTermux

### Styling
terminal-transcript-rows=10000

### Soft keyboard settings
soft-keyboard-toggle-behaviour=enable
use-black-ui=true

### Key bindings
shortcut.create-session=ctrl+t
shortcut.next-session=ctrl+2
shortcut.previous-session=ctrl+1
shortcut.rename-session=ctrl+n

### Extra keys (2 rows)
extra-keys = [ \
  ['ESC', 'TAB', 'CTRL', 'ALT', '-', 'UP', 'DOWN'], \
  ['FN', '/', 'HOME', 'END', 'PGUP', 'PGDN', 'LEFT', 'RIGHT'] \
]
